# Generated by Django 5.1.4 on 2024-12-10 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Place where the habit is performed')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time when the habit has to be performed')),
                ('enjoyable_habit_indicator', models.BooleanField(default='False', verbose_name='Indicator of a enjoyable habit')),
                ('frequency', models.PositiveSmallIntegerField(default=1, verbose_name='Frequency of performance')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reward for performing the habit')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Time to spend on the habit')),
                ('habit_status', models.CharField(choices=[('Pubic', 'Public'), ('Private', 'Private')], default='Private', max_length=50, verbose_name='Habit status')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
